//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortuneTellerApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public int CustomerAge { get; set; }
        public int CustomerBirthMonth { get; set; }
        public int CustomerColor { get; set; }
        public int CustomerSiblings { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Month Month { get; set; }
        public virtual Sibling Sibling { get; set; }
    }
}
